FROM ubuntu:lunar

#Create volume /havoc/bin for compiled firmware binaries
VOLUME /havoc
WORKDIR /havoc/firmware

# Fetch dependencies from APT
RUN apt-get update && \
	apt-get install -y git tar wget dfu-util cmake gcc-arm-none-eabi python3 python3-yaml ccache bzip2 liblz4-tool curl && \
	apt-get -qy autoremove && \
	rm -rf /var/lib/apt/lists/*

#RUN ln -s /usr/bin/python3 /usr/bin/python && \
#	ln -s /usr/bin/pip3 /usr/bin/pip

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Configure CCACHE
RUN mkdir ~/bin && cd ~/bin && \
	for tool in gcc g++ cpp c++;do ln -s $(which ccache) arm-none-eabi-$tool;done

CMD cd .. && cd build && \
	cmake .. && make firmware
